import Provider from '@/SessionProvider'
import './globals.css'
import Navbar from '@/components/Navbar'
import { PrismaClientProvider } from "@prisma/client";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider>
        <Navbar />
      {children}

      </Provider>
      </body>
    </html>
  )
}
